### ISSUE TITLE
Right arrow not clickable

### ISSUE THREAD

**Issue by shivamragnar** [cbgaindia/ckanext-openbudgetsin_theme#57]
In the menu options only the names are clickable and not the arrows. At the top in "Union Dashboard" arrow is clickable and not the name. Making the whole thing confusing.

<img width="813" alt="Menu" src="https://user-images.githubusercontent.com/43090968/97959991-88303680-1dd6-11eb-9fc1-4480c2abc6fd.png">

**Comment by vrnpi** [comment]
The entire area should be clickable not just the words or arrow, even the background behind it. I've made a prototype depicting  the functionality here, https://www.figma.com/proto/b1T3AFvt6rpHrPRDimloXJ/home-page?node-id=412%3A49356&viewport=25%2C397%2C0.16202910244464874&scaling=contain (click on 'dashboards' and go to 'district dashboards').  

Let me know if this clears things out?
