### ISSUE TITLE
Mobile footer alignment

### ISSUE THREAD

**Issue by shivamragnar** [cbgaindia/ckanext-openbudgetsin_theme#60]
Mobile footer seems crowded an unaligned. Also logos does not seem clear at all.

![Mobile Footer](https://user-images.githubusercontent.com/43090968/97960657-e14c9a00-1dd7-11eb-84e1-ce1224da756d.png)

**Comment by vrnpi** [comment]
The mobile footer can be found here, https://www.figma.com/file/b1T3AFvt6rpHrPRDimloXJ/home-page?node-id=383%3A4761. Let me know if you need the mobile footer for a smaller resolution and I will add that in the designs.
