### ISSUE TITLE
Wrong position for screen reader icon tool tip.

### ISSUE THREAD

**Issue by shivamragnar** [cbgaindia/ckanext-openbudgetsin_theme#62]
Position of the screen reader icon tool tip in mobile view, it gets out of the normal view.

![One more thing](https://user-images.githubusercontent.com/43090968/97960956-65068680-1dd8-11eb-8d84-8c9afcf891ca.png)

**Comment by vrnpi** [comment]
@shivamragnar For this, the tooltip should be on the right of the screen with the 'tip' being on the right of the tooltip. I've added the mobile version of the tooltip here, https://www.figma.com/file/b1T3AFvt6rpHrPRDimloXJ/home-page?node-id=772%3A647

In addition, the 'tip' should also have a border-radius of 2px.
