### ISSUE TITLE
Govt. Tiers' cards zooming out instead of zooming in.

### ISSUE THREAD

**Issue by shivamragnar** [cbgaindia/ckanext-openbudgetsin_theme#64]
The government wise budget section has a few cards which seems to be zooming out instead of zooming in like other cards in the homepage.

<img width="1334" alt="Icons" src="https://user-images.githubusercontent.com/43090968/97961355-29b88780-1dd9-11eb-983d-c16ec5221e04.png">

**Comment by vrnpi** [comment]
@shivamragnar The card behaviour for 'government-wise' should follow the same as the other ones; we should scale them rather than zooming out.

**Comment by shivamragnar** [comment]
@vrnpi Yep I have fixed it, will release the latest version and close this issue.
