### ISSUE TITLE
Header drop down disappears sometimes while using it

### ISSUE THREAD

**Issue by shivamragnar** [cbgaindia/ckanext-openbudgetsin_theme#68]
Sometimes the drop down in the header section disappears when we click on a link which is supposed to open nested menu in it. Then again we need to click on the navigation link in the header to get the desired result.

**Comment by vrnpi** [comment]
Hey, I wasn't able to record my screen to show what's happening but it's basically this `removeClass` function that's being called multiple times. This also seems something to do with the 'screen reader' tooltip than to do with the 'dashboard' dropdown
![remove class function that's being called multiple times](https://user-images.githubusercontent.com/53936427/100702020-d67d2900-33c6-11eb-8311-018047b38060.jpg)

**Comment by shivamragnar** [comment]
@vrnpi Even if this is the cause...we can not change this one as it is internal bootstrap function.

**Comment by vrnpi** [comment]
@shivamragnar I get that, I was just curious as to why this function is getting called when we haven't intended to call it.

**Comment by shivamragnar** [comment]
Closing as it is fixed now.
