### ISSUE TITLE
Remove scale effect on hover to avoid heading and content misalignment

### ISSUE THREAD

**Issue by vrnpi** [cbgaindia/ckanext-openbudgetsin_theme#72]
The dashboard heading is accurate in the sense that it accounts for the left padding. And although the code is the same for all other headings, the headings for all other sections are misaligned.

![Misaligned 'key features' and 'budget basics' headings](https://user-images.githubusercontent.com/53936427/98774619-63107900-2411-11eb-80b6-b8a62a85636e.png)

This misalignment has happened because of trying to compensate for the scale effect on hover. We should remove the scaling effect on hover until we figure out a solution that doesn't cause the headings of the different sections to be misaligned.﻿

**Comment by shivamragnar** [comment]
This is one screen shot from the design 
![Screenshot from 2020-11-11 16-02-29](https://user-images.githubusercontent.com/43090968/98801645-168c6400-2438-11eb-9d73-349201644a09.png)

**Comment by vrnpi** [comment]
@shivamragnar I've resolved the spacing issue for 'key feature' cards not having the same padding as the other cards. I've changed the hover state to be more consistent with the other sections as well. You can find all the changes here, https://www.figma.com/file/b1T3AFvt6rpHrPRDimloXJ/home-page?node-id=175%3A1671

**Comment by shivamragnar** [comment]
@vrnpi  Please check the staging server and let me know if it is still there. If not please close the issue.

**Comment by vrnpi** [comment]
Closing the issue
