### ISSUE TITLE
Behaviour of links in header dropdown is not consistent

### ISSUE THREAD

**Issue by vrnpi** [cbgaindia/ckanext-openbudgetsin_theme#79]
The links in the dropdown header are inconsistent, some links are underlined, some links aren't. By default, all links should be underlined. Here are the screenshots of the links in the dropdown

- ![no underline for links under 'OBI portal'](https://user-images.githubusercontent.com/53936427/98775715-ad92f500-2413-11eb-958b-f0f9c219b38e.png)
- ![underline present for links under 'dashboard'](https://user-images.githubusercontent.com/53936427/98775827-dfa45700-2413-11eb-80fc-38af7a322bd2.png)
- ![no underline for links under 'budget datasets'](https://user-images.githubusercontent.com/53936427/98775779-cbf8f080-2413-11eb-8f97-60590e097a8c.png)

Here's the figma file for dropdowns, https://www.figma.com/file/b1T3AFvt6rpHrPRDimloXJ/home-page?node-id=398%3A49710

**Comment by shivamragnar** [comment]
So @vrnpi the links which were the leaf links were not meant to have underlines right. Similar is the case in mobile menu. If it is different for both, do let me know.

**Comment by vrnpi** [comment]
@shivamragnar all links must be underlined. The leaf links won't have the arrows.

**Comment by shivamragnar** [comment]
Sure and thanks will update once it is there.
