### ISSUE TITLE
Dropdown bug on hover

### ISSUE THREAD

**Issue by vrnpi** [cbgaindia/ckanext-openbudgetsin_theme#84]
Noticed a weird bug with the dropdown on desktop. When the dropdown is open and there's a mouse hover, the dropdown position changes.
![dropdown shifts on mouse hover](https://user-images.githubusercontent.com/53936427/100337944-fb0b8680-2ffd-11eb-975b-9c2c511298fc.gif)

**Comment by vrnpi** [comment]
The hover bug is caused by a `margin-top: 0` being inserted on `hover` for the `dropdown` class. We should either comment it out or remove it entirely
```
dropdown:hover .dropdown-menu {
    margin-top: 0; /* we need to remove this line of code */
}
```

**Comment by shivamragnar** [comment]
Closing as it is fixed now.
