### ISSUE TITLE
'Budget basics' card needs to be clickable

### ISSUE THREAD

**Issue by vrnpi** [cbgaindia/ckanext-openbudgetsin_theme#85]
We need the entire 'budget basics' card needs to be clickable not just the button.

![ezgif com-crop](https://user-images.githubusercontent.com/53936427/100338580-c64bff00-2ffe-11eb-812f-d298260cca61.gif)

**Comment by shivamragnar** [comment]
@vrnpi  Well if both of the card and the button are clickable and taking the user to the same link, do you think we can drop button or make it non clickable ?

**Comment by vrnpi** [comment]
You're right. We should make the entire card clickable and remove the hover and active states for the button and change it to a link in code.

**Comment by shivamragnar** [comment]
Closing as it is fixed now.
