### ISSUE TITLE
Extra `:before` class for dropdown arrow

### ISSUE THREAD

**Issue by vrnpi** [cbgaindia/ckanext-openbudgetsin_theme#87]
I was working on some other issues for the dropdown and noticed we have an extra arrow because of a `:before` class that we don't need. I've modified the image to show the extra arrow, it's harder to spot it otherwise.

![extra arrow caused by a before class](https://user-images.githubusercontent.com/53936427/100701329-6e7a1300-33c5-11eb-9f93-154b77d56a53.png)

**Comment by shivamragnar** [comment]
Hey @vrnpi  Thanks for pointing out. This is from the previous styles which i haven't touched. I will remove this one.

**Comment by shivamragnar** [comment]
Closing as it is fixed now.
