### ISSUE TITLE
Mobile Header | Home Page

### ISSUE THREAD

**Issue by TheDataAreClean** [cbgaindia/ckanext-openbudgetsin_theme#91]
**Issue Details**
- Icon for mobile menu post redisign looks compressed. 
- The hamburger menu icon looks out of place.

**Device Details**
iPhone XS / iOS14 / Firefox

![image](https://user-images.githubusercontent.com/11213505/101431981-062fb200-392e-11eb-915c-ba13f2bcf0d7.png)

**Comment by shivamragnar** [comment]
Closing as fixed.
