### ISSUE TITLE
Hamburger Menu | Non Responsive

### ISSUE THREAD

**Issue by TheDataAreClean** [cbgaindia/ckanext-openbudgetsin_theme#92]
**Issue Details**
- Hamburger menu icons not available on the following pages, also non-responsive
[URL - How To Use](https://openbudgetsindia.org/pages/how-to-use-the-portal)
[URL - FAQs](https://openbudgetsindia.org/pages/faqs)
![image](https://user-images.githubusercontent.com/11213505/101432681-4c394580-392f-11eb-922a-2dfa5dfef498.png)

- Hamburger menu icons non-responsive on the pages available
[URL - About](https://openbudgetsindia.org/about)
![image](https://user-images.githubusercontent.com/11213505/101432500-f6649d80-392e-11eb-9ab6-360a6c396f00.png)

**Device Details**
iPhone XS / iOS14 / Firefox

**Comment by shivamragnar** [comment]
Closing as fixed.
