### ISSUE TITLE
Assets breaking in nested pages - Tested in Header

### ISSUE THREAD

**Issue by shashank-sharma** [cbgaindia/ckanext-openbudgetsin_theme#93]
Issue: Assets like SVG in header failed to be fetched in pages other than homepage because of relative path: [here](https://github.com/cbgaindia/ckanext-openbudgetsin_theme/blob/761a5cddf724c341e85150d196cf10dfcee8d7a2/ckanext/openbudgetsin_theme/templates/header.html#L17)

Impact:
1. Correct images are not getting served
2. Slows down the page

![Screenshot from 2020-12-08 16-47-15](https://user-images.githubusercontent.com/9320644/101477306-0e5f1000-3975-11eb-805c-88777cc3f1ee.png)

**Comment by shivamragnar** [comment]
Closing as fixed.
